services:
  - type: web
    name: social-media-api
    runtime: python
    rootDir: social_media_api
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn social_media_api.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: social-media-db
          property: connectionString
    autoDeploy: true

databases:
  - name: social-media-db
    databaseName: social_media_db
    user: social_media_user
